version: "3"
services:
  mysql-service-order:
    container_name: mysql-box-order
    image: percona:ps-5.6
    networks:
      - mysql-network-order
    volumes:
      - type: bind
        source: /home/cpandey/projects/docker-data/restaurant/order/mysql/data
        target: /var/lib/mysql
        volume:
          nocopy: true          
      - type: bind
        source: /home/cpandey/projects/docker-data/restaurant/order/mysql/script/orderdb.sql
        target: /docker-entrypoint-initdb.d/1.sql
        volume:
          nocopy: true    

    restart: always
    ports: 
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=badeploy
      - MYSQL_PASSWORD=badeploy123
      - MYSQL_DATABASE=orderdb
  web-service:
    container_name: order-service
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /home/cpandey/projects/docker-data/restaurant/order/logs
        target: /opt/multimoduleprojects/restaurant/logs
        volume:
           nocopy: true
    ports:
      - "2001:20003"
    networks:
      - mysql-network-order
    depends_on:
      - mysql-service-order

networks:
   mysql-network-order:
    driver: bridge    